image:
  repository: redis
  tag: "7"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 6379

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""

resources: {}

config:
  redis.conf: |
    appendonly yes
    save 900 1
    save 300 10
    save 60 10000
